//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mtgdb.Gui.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mtgdb.Gui.Resx.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ava {
            get {
                object obj = ResourceManager.GetObject("ava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Box20 {
            get {
                object obj = ResourceManager.GetObject("Box20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart2_16x16 {
            get {
                object obj = ResourceManager.GetObject("chart2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clone24 {
            get {
                object obj = ResourceManager.GetObject("Clone24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclude_minus24t {
            get {
                object obj = ResourceManager.GetObject("exclude_minus24t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + SPACE - intellisense, F1 - help....
        /// </summary>
        internal static string FindEditor_Prompt {
            get {
                return ResourceManager.GetString("FindEditor_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forge_32 {
            get {
                object obj = ResourceManager.GetObject("forge_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge {type}.
        /// </summary>
        internal static string Formatter_ForgeDeck_Description {
            get {
                return ResourceManager.GetString("Formatter_ForgeDeck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magarena {type}.
        /// </summary>
        internal static string Formatter_MagarenaDeck_Description {
            get {
                return ResourceManager.GetString("Formatter_MagarenaDeck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic The Gathering Online {type}.
        /// </summary>
        internal static string Formatter_MtgoDeck_Description {
            get {
                return ResourceManager.GetString("Formatter_MtgoDeck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMage {type}.
        /// </summary>
        internal static string Formatter_XMageDeck_Description {
            get {
                return ResourceManager.GetString("Formatter_XMageDeck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hidden24 {
            get {
                object obj = ResourceManager.GetObject("hidden24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ieroglif_32 {
            get {
                object obj = ResourceManager.GetObject("ieroglif_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap include_plus24e {
            get {
                object obj = ResourceManager.GetObject("include_plus24e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap index_16x16 {
            get {
                object obj = ResourceManager.GetObject("index_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Legality20 {
            get {
                object obj = ResourceManager.GetObject("Legality20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Magarena_32 {
            get {
                object obj = ResourceManager.GetObject("Magarena_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap manacost24ctc {
            get {
                object obj = ResourceManager.GetObject("manacost24ctc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap manatext25i {
            get {
                object obj = ResourceManager.GetObject("manatext25i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maximize {
            get {
                object obj = ResourceManager.GetObject("maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize {
            get {
                object obj = ResourceManager.GetObject("minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mtg20 {
            get {
                object obj = ResourceManager.GetObject("mtg20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mtg32 {
            get {
                object obj = ResourceManager.GetObject("mtg32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap na {
            get {
                object obj = ResourceManager.GetObject("na", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap normalize {
            get {
                object obj = ResourceManager.GetObject("normalize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open2_16x16 {
            get {
                object obj = ResourceManager.GetObject("open2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paypal_32 {
            get {
                object obj = ResourceManager.GetObject("paypal_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_card_48 {
            get {
                object obj = ResourceManager.GetObject("play_card_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print_16x16 {
            get {
                object obj = ResourceManager.GetObject("print_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap properties_16x16 {
            get {
                object obj = ResourceManager.GetObject("properties_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redo_16x16 {
            get {
                object obj = ResourceManager.GetObject("redo_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rightclick32 {
            get {
                object obj = ResourceManager.GetObject("rightclick32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_16x16 {
            get {
                object obj = ResourceManager.GetObject("save_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap showhidecomment_16x16 {
            get {
                object obj = ResourceManager.GetObject("showhidecomment_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shown24 {
            get {
                object obj = ResourceManager.GetObject("shown24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_32 {
            get {
                object obj = ResourceManager.GetObject("sort_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stretch20bw {
            get {
                object obj = ResourceManager.GetObject("Stretch20bw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banned.
        /// </summary>
        internal static string Title_Banned {
            get {
                return ResourceManager.GetString("Title_Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indexing {0}: {1} / {2}.
        /// </summary>
        internal static string Title_building_index {
            get {
                return ResourceManager.GetString("Title_building_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cards.
        /// </summary>
        internal static string Title_building_index_cards {
            get {
                return ResourceManager.GetString("Title_building_index_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intellisense.
        /// </summary>
        internal static string Title_building_index_intellisense {
            get {
                return ResourceManager.GetString("Title_building_index_intellisense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keywords.
        /// </summary>
        internal static string Title_building_index_keywords {
            get {
                return ResourceManager.GetString("Title_building_index_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending index load....
        /// </summary>
        internal static string Title_building_index_pending {
            get {
                return ResourceManager.GetString("Title_building_index_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending keyword search....
        /// </summary>
        internal static string Title_building_keywords_pending {
            get {
                return ResourceManager.GetString("Title_building_keywords_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck: {0}.
        /// </summary>
        internal static string Title_deck_size_0_ {
            get {
                return ResourceManager.GetString("Title_deck_size_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ custom filter not set ].
        /// </summary>
        internal static string Title_filter_empty {
            get {
                return ResourceManager.GetString("Title_filter_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot report.
        /// </summary>
        internal static string Title_form_pivot {
            get {
                return ResourceManager.GetString("Title_form_pivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illegal.
        /// </summary>
        internal static string Title_Illegal {
            get {
                return ResourceManager.GetString("Title_Illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legal.
        /// </summary>
        internal static string Title_Legal {
            get {
                return ResourceManager.GetString("Title_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading keywords....
        /// </summary>
        internal static string Title_loading_keywords {
            get {
                return ResourceManager.GetString("Title_loading_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string Title_mode_and {
            get {
                return ResourceManager.GetString("Title_mode_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignored .
        /// </summary>
        internal static string Title_mode_ignored {
            get {
                return ResourceManager.GetString("Title_mode_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not set.
        /// </summary>
        internal static string Title_mode_no_input {
            get {
                return ResourceManager.GetString("Title_mode_no_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Title_mode_or {
            get {
                return ResourceManager.GetString("Title_mode_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modified, press ENTER to apply.
        /// </summary>
        internal static string Title_mode_search_string_is_modified {
            get {
                return ResourceManager.GetString("Title_mode_search_string_is_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restricted.
        /// </summary>
        internal static string Title_Restricted {
            get {
                return ResourceManager.GetString("Title_Restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cards scroll: {0}.
        /// </summary>
        internal static string Title_scroll_cards_0_ {
            get {
                return ResourceManager.GetString("Title_scroll_cards_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deck scroll: {0}.
        /// </summary>
        internal static string Title_scroll_deck_0_ {
            get {
                return ResourceManager.GetString("Title_scroll_deck_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sets: {0,3:000}.
        /// </summary>
        internal static string Title_sets_0_ {
            get {
                return ResourceManager.GetString("Title_sets_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syntax error.
        /// </summary>
        internal static string Title_syntax_error {
            get {
                return ResourceManager.GetString("Title_syntax_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash_16x16 {
            get {
                object obj = ResourceManager.GetObject("trash_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo_16x16 {
            get {
                object obj = ResourceManager.GetObject("undo_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_bw {
            get {
                object obj = ResourceManager.GetObject("update_bw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_zoom_in {
            get {
                object obj = ResourceManager.GetObject("view_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xmage_32 {
            get {
                object obj = ResourceManager.GetObject("xmage_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YandexMoney_32 {
            get {
                object obj = ResourceManager.GetObject("YandexMoney_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
